(cl:in-package sbg_driver-msg)
(cl:export '(SOLUTION_MODE-VAL
          SOLUTION_MODE
          ATTITUDE_VALID-VAL
          ATTITUDE_VALID
          HEADING_VALID-VAL
          HEADING_VALID
          VELOCITY_VALID-VAL
          VELOCITY_VALID
          POSITION_VALID-VAL
          POSITION_VALID
          VERT_REF_USED-VAL
          VERT_REF_USED
          MAG_REF_USED-VAL
          MAG_REF_USED
          GPS1_VEL_USED-VAL
          GPS1_VEL_USED
          GPS1_POS_USED-VAL
          GPS1_POS_USED
          GPS1_COURSE_USED-VAL
          GPS1_COURSE_USED
          GPS1_HDT_USED-VAL
          GPS1_HDT_USED
          GPS2_VEL_USED-VAL
          GPS2_VEL_USED
          GPS2_POS_USED-VAL
          GPS2_POS_USED
          GPS2_COURSE_USED-VAL
          GPS2_COURSE_USED
          GPS2_HDT_USED-VAL
          GPS2_HDT_USED
          ODO_USED-VAL
          ODO_USED
))