(cl:in-package sbg_driver-msg)
(cl:export '(PORT_A-VAL
          PORT_A
          PORT_B-VAL
          PORT_B
          PORT_C-VAL
          PORT_C
          PORT_D-VAL
          PORT_D
          PORT_E-VAL
          PORT_E
          PORT_A_RX-VAL
          PORT_A_RX
          PORT_A_TX-VAL
          PORT_A_TX
          PORT_B_RX-VAL
          PORT_B_RX
          PORT_B_TX-VAL
          PORT_B_TX
          PORT_C_RX-VAL
          PORT_C_RX
          PORT_C_TX-VAL
          PORT_C_TX
          PORT_D_RX-VAL
          PORT_D_RX
          PORT_D_TX-VAL
          PORT_D_TX
          PORT_E_RX-VAL
          PORT_E_RX
          PORT_E_TX-VAL
          PORT_E_TX
          CAN_RX-VAL
          CAN_RX
          CAN_TX-VAL
          CAN_TX
          CAN_STATUS-VAL
          CAN_STATUS
))